#! /bin/groovy

// nodes
def NODE_DOCKER_LINUX = "grbuild14"
def WORK_DIR_NODE_DOCKER_LINUX

// Environment
def WORKER_TOOL_REPOSITORY_URL = "git@github.dev.cybozu.co.jp:tuyen-nguyen/work_tools.git"
def GAROON_REPOSITORY_URL = "git@github.dev.cybozu.co.jp:garoon/garoon.git"
def GAROON_JENKIN_CREDENTIAL_ID = "jenkins-github-deploy-key"

// Input Parameters
def GIT_BRANCH = "${BRANCH}"
//def IS_FORCE_BINARY_COMPILE = Boolean.valueOf("${IS_FORCE_BINARY_COMPILE}")
//def ARCHIVE_WINDOWS = Boolean.valueOf("${ARCHIVE_WINDOWS}")

// process
try {
    timeout(time: 120, unit: 'MINUTES') {
        stage("Checkout") {
            node(NODE_DOCKER_LINUX) {
                dir("${env.WORKSPACE}") {
                    sh "rm -rf *"
                }

                // Specify working directory
                // Because parallel execution fails if we don't do it at each time
                WORK_DIR_NODE_DOCKER_LINUX = "${env.WORKSPACE}/${env.BUILD_ID}"
                dir(WORK_DIR_NODE_DOCKER_LINUX) {
                    // checkout deploy tool
                    checkout([
                            $class                           : "GitSCM",
                            branches                         : [[name: "origin/deploy-onpre-servicepack"]],
                            doGenerateSubmoduleConfigurations: false,
                            //clearWorkspace                   : true,
                            extensions                       : [
                                    //[$class: "GitLFSPull"],
                                    [$class: "CleanBeforeCheckout"],
                                    [$class: 'RelativeTargetDirectory', relativeTargetDir: 'auto-deploy'],
                            ],
                            submoduleCfg                     : [],
                            userRemoteConfigs                : [
                                    [
                                        credentialsId: GAROON_JENKIN_CREDENTIAL_ID,
                                        url: WORKER_TOOL_REPOSITORY_URL
                                    ]
                            ]
                        ])

                    // check out Garoon branch
                    echo "GIT_BRANCH: ${GIT_BRANCH}"
                    checkout([
                        $class                           : "GitSCM",
                        branches                         : [[name: "origin/${GIT_BRANCH}"]],
                        doGenerateSubmoduleConfigurations: false,
                        clearWorkspace                   : true,
                        extensions                       : [
                                [$class: "GitLFSPull"],
                                [$class: "CleanBeforeCheckout"],
                                [$class: 'RelativeTargetDirectory', relativeTargetDir: 'garoon'],
                        ],
                        submoduleCfg                     : [],
                        userRemoteConfigs                : [
                                [
                                    credentialsId: GAROON_JENKIN_CREDENTIAL_ID,
                                    url: GAROON_REPOSITORY_URL
                                ]
                        ]
                    ])

                    
                    //GIT_BRANCH_REVISION = sh(returnStdout: true, script: "git rev-parse HEAD").trim()
                    //echo "GIT_BRANCH_REVISION: " + GIT_BRANCH_REVISION

                    //GIT_BUILD_REVISION = sh(returnStdout: true, script: "git log --oneline -n 1 ./build/binary | cut -c 1-7 | xargs git rev-parse").trim()
                    //echo "GIT_BUILD_REVISION: " + GIT_BUILD_REVISION
                }

                dir(WORK_DIR_NODE_DOCKER_LINUX) {
                    if (fileExists('garoon/build/build.conf')) {
                        sh "cp -rf garoon/build/build.conf auto-deploy"
                    }
                    if (fileExists('garoon/build_sp/build_sp.conf')) {
                        sh "cp -rf garoon/build_sp/build_sp.conf auto-deploy"
                    }
                }

            }

            currentBuild.description = "<li>target: ${GIT_BRANCH}"
        }
    }
} catch (err) {

} finally {

}